version: '3'

services:
  nginx-interview:
    image: 'nginx:stable'
    container_name: nginx-interview
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - interview-docker

  php-interview:
    container_name: php-interview
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - interview-docker
  
  mysql-interview:
    container_name: mysql-interview
    image: mysql:8.0.29
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD=rootL
      - MYSQL_DATABASE=interview
      - MYSQL_USER=tranbinhan
      - MYSQL_PASSWORD=123456
    expose:
      - 3306
    networks:
      - interview-docker
  
  phpmyadmin-interview:
    container_name: phpmyadmin-interview
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - MYSQL_ROOT_PASSWORD=rootL
      - PMA_USER=root
      - PMA_PASSWORD=rootL
      - PMA_HOST=mysql-interview
    depends_on:
      - mysql-interview
    networks:
      - interview-docker

  mailhog-interview:
    container_name: mailhog-interview
    restart: always
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1225:1025
      - 8225:8025
    networks:
      - interview-docker

networks:
  interview-docker: